services:
  flask_app:
    build: 
      context: ./source
      dockerfile: dockerfile # Path is relative to the context above
    environment:
      # Map format (no dashes at the start)
      DB_PASSWORD_FILE: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: postgres:18 # Note: postgres:18 doesn't exist yet! (Current is 17)
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - database


